"""Initial model

Revision ID: 465c2a73051
Revises: None
Create Date: 2015-10-02 13:34:51.754775

"""

# revision identifiers, used by Alembic.
revision = '465c2a73051'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timing', sa.Integer(), nullable=True),
    sa.Column('persons', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    ### end Alembic commands ###
